### ISSUE TITLE
När nya karta öppnas måste platser tömmas & samma vid inläsning av nya platser.

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/AssignmentMap#12]
Only thing is the dialog pop-up. Boolean "change" needs to set true.
be60d744e18db39d81c4386802f8cbb633101907
Solved!

**Comment by jasonserviss** [comment]
This is actually not in the assignments instructions, although it would make sense that this is part of the functionality. It shouldn't be too hard to fix I would think. Fix other issues first.

**Comment by OliviaImner** [comment]
Here is the assignment criteria: 
Obs att både New Map och Load Places kan väljas även när man har en karta inladdad och platser skapade. I så fall måste det aktuella ”dokumentet” avslutas innan det nya kan användas.

**Comment by jasonserviss** [comment]
Ok, but that doesn't specifically state that "platser måste tömmas" although it depends a bit on how you interpret the instructions, i.e. what is ment with "dokumentet". What is it that "avslutas" now when new map or load places is chosen?

**Comment by OliviaImner** [comment]
4d20e00bfcdb94f673dc89d10951bd38fe896604 
When a new map is created the places are deleted and the new map are exposed.

**Comment by OliviaImner** [comment]
21135cfbbf20fa49fc1e17f3afbde6a976ef9732
Removed all old places when a new file is opened.

**Comment by OliviaImner** [comment]
2be5e938a5234ab49c954b208394d31f2b8d7833
Fixed again, it was the JScrollPane that was the problem.
