### ISSUE TITLE
Trianglarna ritas ut på fel plats. 

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/AssignmentMap#13]
Spetsen ska vara där övre vänstra hörnet är. Det syns tydlig om du använder Hendriks karta+testfil, där spetsen på platsen 142,233 pekar fel.

**Comment by jasonserviss** [comment]
This seems like an issue with the functionality and should be fixed. Initially it would appear that this is specified according to the following in the assignments criteria: 

> Obs den lilla komplikationen att platsens grafiska area räknas från dess övre vänstra hörn, medan platsens position enligt denna tillämpning är triangelns nedre spets. Det kräver lite omräkning av koordinater.

**Comment by OliviaImner** [comment]
3d60d8608c9a97124b8db96ce8af413a349a072c
