### ISSUE TITLE
Ingen varning om osparade ändringar vid avslut.

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/AssignmentMap#6]
Uppgifttext: Exit ska avsluta programexekveringen. Programmet ska även kunna avslutas via stängningsrutan. Om det finns osparade förändringar ska det visas en dialogruta som varnar om att det finns osparade ändringar och frågar om man ändå vill avsluta – användaren har då möjligheten att avbryta operationen.

**Comment by jasonserviss** [comment]
Fixed in commit: 46b8027b8fa3fe2d860648fcd37d283bff31b2b5
